### ISSUE TITLE
Missing Vault token in Nomad servers

### ISSUE THREAD

**Issue by lgfa29** [nunchistudio/hashibox#1]
### What OS are you using?

macOS

### Unexpected behavior

Nomad servers are not able to start due to missing [Vault token](https://www.nomadproject.io/docs/configuration/vault#token)

### Steps to reproduce

```console
$ make init
```

Navigate to a Nomad server (e.g. http://192.168.60.10:4646/)

### Expected behavior

The Nomad UI is displayed.

### Logs

```console
$ vagrant ssh node-server-1
$ journalctl -u nomad
Feb 06 20:14:25 node-server-1 systemd[1]: Started "HashiCorp Nomad".
Feb 06 20:14:25 node-server-1 nomad[15561]: ==> Loaded configuration from /hashibox/defaults/nomad/config/defaults.hcl, /hashibox/overrides/nomad/config/overrides.hcl
Feb 06 20:14:25 node-server-1 nomad[15561]: ==> Starting Nomad agent...
Feb 06 20:14:25 node-server-1 nomad[15561]: ==> Error starting agent: server setup failed: Failed to setup Vault client: Vault token must be set
Feb 06 20:14:25 node-server-1 nomad[15561]:     2022-02-06T20:14:25.833Z [WARN]  agent.plugin_loader: skipping external plugins since plugin_dir doesn't exist: plugin_dir=/opt/nomad/plugins
Feb 06 20:14:25 node-server-1 nomad[15561]:     2022-02-06T20:14:25.837Z [INFO]  agent: detected plugin: name=raw_exec type=driver plugin_version=0.1.0
Feb 06 20:14:25 node-server-1 nomad[15561]:     2022-02-06T20:14:25.837Z [INFO]  agent: detected plugin: name=exec type=driver plugin_version=0.1.0
Feb 06 20:14:25 node-server-1 nomad[15561]:     2022-02-06T20:14:25.837Z [INFO]  agent: detected plugin: name=qemu type=driver plugin_version=0.1.0
Feb 06 20:14:25 node-server-1 nomad[15561]:     2022-02-06T20:14:25.837Z [INFO]  agent: detected plugin: name=java type=driver plugin_version=0.1.0
Feb 06 20:14:25 node-server-1 nomad[15561]:     2022-02-06T20:14:25.837Z [INFO]  agent: detected plugin: name=docker type=driver plugin_version=0.1.0
Feb 06 20:14:25 node-server-1 nomad[15561]:     2022-02-06T20:14:25.837Z [INFO]  nomad: shutting down server
```

**Comment by loicsaintroch** [comment]
Thank you @lgfa29 for trying this out.

As written at the end of the [Installation](https://github.com/nunchistudio/hashibox/blob/main/documentation/installation.md) document:
> Vault is not yet initialized. Therefore, Vault health checks don't pass and Nomad can't properly run since it's configured to integrate with Vault.

Did you follow the [Vault initialization](https://github.com/nunchistudio/hashibox/blob/main/documentation/vault-init.md) document after? Do you have a suggestion to improve or automate this onboarding?

**Comment by lgfa29** [comment]
Oh, of course there is, sorry I missed that 😅

I saw the table with the URLs and started clicking on then, which moved me away from the instructions, and then I went debugging.

Maybe move the Vault notice before the table with the links? But the steps are all there, it was my fault that I missed.

Thanks for the reply!

**Comment by loicsaintroch** [comment]
No problem, thanks for the feedback. 😉

I just improved the documentation and navigation between steps. It should be easier to follow now.

**Comment by lgfa29** [comment]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/775380/153021559-3d40c15e-1df5-4cce-93bc-aaebe63181d6.png">

All green after actually following the instructions 😅 🥳
